# Generated by Django 2.1 on 2018-08-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('insured', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('attachments', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m', verbose_name='Image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
